const mongoose = require('mongoose');

const schema = new mongoose.Schema({
    mpn_channel : String,
    mpn_mpns : [String],
    mpn_status : String,
    mpn_changeDate: String,
    mpn_GST : String,
    mpn_image: String,
    company_uom: String,
    company_unitsPack: Number,
    company_packsCarton : Number,
    company_name: String,
    company_brand : String,
    company_abbreviation : String,
    medisa_title: String,
    medisa_url: String,
    medisa_serpRank: String,
    medisa_sku: String,
    medisa_uip: String,
    medisa_stock: String,
    medisa_price : String,
    ind_title: String,
    ind_url: String,
    ind_sku: String,
    ind_uip: String,
    ind_stock: String,
    ind_sellPrice: String,
    ind_buyPrice: String,
    teammed_title: String,
    teammed_url: String,
    teammed_uip: String,
    teammed_stock: String,
    teammed_sellPrice: String,
    teammed_buyPrice: String,
    main_title: String,
    main_url: String,
    main_uip: String,
    main_stock: String,
    main_sellPrice: String,
    main_buyPrice: String,
    brightSky_title: String,
    brightSky_url: String,
    brightSky_uip: String,
    brightSky_stock: String,
    brightSky_price: String,
    joya_title: String,
    joya_url: String,
    joya_uip: String,
    joya_stock: String,
    joya_price: String,
    alpha_title: String,
    alpha_url: String,
    alpha_uip: String,
    alpha_stock: String,
    alpha_price: String,
    medshop_title: String,
    medshop_url: String,
    medshop_uip: String,
    medshop_stock: String,
    medshop_price: String,
})


const csvSave = mongoose.model("csv", schema)

module.exports = csvSave